yolo_model:

  config_file:
    name: yolov3_custom_tiny.cfg
  weight_file:
    name: yolov3_custom_tiny.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Weed
      - Broccoli
      - YoungBroccoli
    
